---
title: Decision Analysis Workshop 
subtitle: Istanbul, Turkey 2024
editor: visual
format: 
  html:
    link-external-newwindow: true
css: styles.css
editor_options: 
  chunk_output_type: console
bibliography: references.bib
---

# Schedule

+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Day                    | Time           | Topic                                                                                                                                                                                                                                                                                                                                                                                                                         |
+========================+================+===============================================================================================================================================================================================================================================================================================================================================================================================================================+
| 27/09/2024 (Friday)    | 08:15 - 9:15   | Registration and Introductions \[JG\]                                                                                                                                                                                                                                                                                                                                                                                         |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 09:15 - 10:30  | [Conceptual and Theoretical Foundations for Decision Analysis and Cost Effectiveness Analysis](lec_1a.introduction-to-decision-analysis.qmd)                                                                                                                                                                                                                                                                                  |
|                        |                |                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                        |                | \[AL, JZ\] \[[2022 version](https://vchem-vital-workshop-2022.netlify.app/lectures/lec_conceptual-and-theoretical-frameworks#/title-slide)\] \[[2022 version #2](https://vchem-vital-workshop-2022.netlify.app/lectures/lec_foundations-of-cost-effectiveness-analysis#/title-slide)\] \[[2023 Nigeria](https://graveja0.github.io/v-brch-nigeria-2023/lectures/lec_1a.introduction-to-decision-analysis.html#/title-slide)\] |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 10:30 - 10:50  | Coffee/Tea Break                                                                                                                                                                                                                                                                                                                                                                                                              |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 10:50 - 12:00  | [Decision Trees](lectures/lec_2.decision-trees-and-probabilities.qmd)                                                                                                                                                                                                                                                                                                                                                         |
|                        |                |                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                        |                | \[AL\] \[[2023 Nigeria Version](https://graveja0.github.io/v-brch-nigeria-2023/lectures/lec_2.decision-trees-and-probabilities.html#/title-slide)\]                                                                                                                                                                                                                                                                           |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 12:00 - 13:15  | Lunch                                                                                                                                                                                                                                                                                                                                                                                                                         |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 13:15 - 14:30  | [Bayes Theorem and Probability Revision](lectures/lec_3a.bayes-probrevision.qmd)                                                                                                                                                                                                                                                                                                                                              |
|                        |                |                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                        |                | \[JG\]                                                                                                                                                                                                                                                                                                                                                                                                                        |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 14:30 - 15:30  | [Case Study: Decision Trees in Amua](lectures/cs_decision-tree-amua.qmd)                                                                                                                                                                                                                                                                                                                                                      |
|                        |                |                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                        |                | \[JZ\]                                                                                                                                                                                                                                                                                                                                                                                                                        |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 15:30 - 16:45  | Capstone - Guided exercise                                                                                                                                                                                                                                                                                                                                                                                                    |
|                        |                |                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                        |                | \[CW, MM\] \[Objectives & Deliverables TBD\]                                                                                                                                                                                                                                                                                                                                                                                  |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 16:45 - 17:00  | Daily Recap Discussion                                                                                                                                                                                                                                                                                                                                                                                                        |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 28/09/2024 (Saturday)  | 08:15 - 10:00  | Capstone: Construct Decision Tree in Amua                                                                                                                                                                                                                                                                                                                                                                                     |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 10:00 - 10:30  | Tea Break                                                                                                                                                                                                                                                                                                                                                                                                                     |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 10:30 - 12:00  | [CEA Fundamentals 1: Costs](lectures/lec_5a.cea-fundamentals1.qmd)                                                                                                                                                                                                                                                                                                                                                            |
|                        |                |                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                        |                | \[AL\] \[[2023 Nigeria version](https://graveja0.github.io/v-brch-nigeria-2023/lectures/lec_5a.cea-fundamentals1.html#/title-slide)\]                                                                                                                                                                                                                                                                                         |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 12:00 - 13:15  | Lunch                                                                                                                                                                                                                                                                                                                                                                                                                         |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 13:15 - 15:00  | [CEA Fundamentals 2: Health Outcomes](lectures/lec_5b.cea-fundamentals2.qmd)                                                                                                                                                                                                                                                                                                                                                  |
|                        |                |                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                        |                | \[JZ\] \[[2023 Nigeria Version](https://graveja0.github.io/v-brch-nigeria-2023/lectures/lec_5b.cea-fundamentals2.html#/title-slide)\]                                                                                                                                                                                                                                                                                         |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 15:00 - 15:30  | Daily Recap and Group Discussion                                                                                                                                                                                                                                                                                                                                                                                              |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 15:30 - 17:00  | Capstone - Group Work                                                                                                                                                                                                                                                                                                                                                                                                         |
|                        |                |                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                        |                | \[Objectives & Deliverables TBD\]                                                                                                                                                                                                                                                                                                                                                                                             |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 30/09/2024 (Monday)    | 08:15 - 10:00  | Capstone - Paired Group Discussion                                                                                                                                                                                                                                                                                                                                                                                            |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 09:30 - 10:30  | Tea Break                                                                                                                                                                                                                                                                                                                                                                                                                     |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 10:30 - 12:00  | [CEA Fundamentals 3: Incremental CEA](lectures/lec_6.ICERs.qmd)                                                                                                                                                                                                                                                                                                                                                               |
|                        |                |                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                        |                | \[AL\] \[[2022 Version](https://vchem-vital-workshop-2022.netlify.app/lectures/lec_incremental-cea#/title-slide)\] \[[2023 Nigeria version](https://graveja0.github.io/v-brch-nigeria-2023/lectures/lec_6.ICERs.html#/title-slide)\]                                                                                                                                                                                          |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 12:00 - 13:15  | Lunch                                                                                                                                                                                                                                                                                                                                                                                                                         |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 13:15- 14:45   | Case Study: Incremental CEA                                                                                                                                                                                                                                                                                                                                                                                                   |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 14:45 - 15:45  | [Lecture: Curating Model Parameters](lectures/lec_parameters.qmd)                                                                                                                                                                                                                                                                                                                                                             |
|                        |                |                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                        |                | \[JG\]                                                                                                                                                                                                                                                                                                                                                                                                                        |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 15:45 - 16:15  | Daily Recap and Group Discussion                                                                                                                                                                                                                                                                                                                                                                                              |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 16:15 - 17:00  | Capstone - Group Work                                                                                                                                                                                                                                                                                                                                                                                                         |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 01/10/2024 (Tuesday)   | 08:15 - 10:30  | [Markov Models](lectures/lec_7.MarkovModels1.qmd) \[JG\] \[[2022 Version](https://vchem-vital-workshop-2022.netlify.app/lectures/lec_markov#/title-slide)\] \[[2023 Nigeria version](https://graveja0.github.io/v-brch-nigeria-2023/lectures/lec_7.MarkovModels1.html#/title-slide)\]                                                                                                                                         |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 10:30 - 11:00  | Break                                                                                                                                                                                                                                                                                                                                                                                                                         |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 11:00 - 12:00  | [Case Study: Alive-Dead Markov Model in Amua](case-studies/cs_markov_alive-dead.qmd)                                                                                                                                                                                                                                                                                                                                          |
|                        |                |                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                        |                | \[GR: Need to incorporate .csv files\]                                                                                                                                                                                                                                                                                                                                                                                        |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 12:00 - 13:15  | Lunch                                                                                                                                                                                                                                                                                                                                                                                                                         |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 13:15 - 14:45  | [Lecture: Structuring the Markov Model](lectures/lec_structure.qmd)                                                                                                                                                                                                                                                                                                                                                           |
|                        |                |                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                        |                | \[JG\]                                                                                                                                                                                                                                                                                                                                                                                                                        |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 14:45 - 16:00  | Case Study: Progressive Disease Model                                                                                                                                                                                                                                                                                                                                                                                         |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 16:00 - 16:15  | Group Discussion: Progressive Disease Model                                                                                                                                                                                                                                                                                                                                                                                   |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 16:15-17:00    | Capstone Group Work: Specify a Markov Model                                                                                                                                                                                                                                                                                                                                                                                   |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 02/10/2024 (Wednesday) | 08:15 - 09:30  | [Interactive Lecture / Case Study: CEAs, One- and Two-way Sensitivity](lectures/lec_sensitivity.qmd),                                                                                                                                                                                                                                                                                                                         |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 09:30 - 10:15  | Interactive Lecture / Threshold and Scenario Analysis Analysis \[JG\] \[[2022 Lecture](https://vchem-vital-workshop-2022.netlify.app/lectures/lec_sensitivity_scenario#/title-slide)\] \[[2023 Nigeria Version](https://graveja0.github.io/v-brch-nigeria-2023/lectures/lec_sensitivity.html#/title-slide)\]                                                                                                                  |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 10:15 - 10:30  | Break                                                                                                                                                                                                                                                                                                                                                                                                                         |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 10:30 - 12:00  | Interactive Lecture / Case Study: Probabilistic Sensitivity Analysis \[JG\] \[[2022 Lecture](https://vchem-vital-workshop-2022.netlify.app/lectures/lec_psa#/title-slide)\]                                                                                                                                                                                                                                                   |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 12:00 - 13:15  | Lunch                                                                                                                                                                                                                                                                                                                                                                                                                         |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 13:15 - 15:00  | Prepare Final Capstone Presentations                                                                                                                                                                                                                                                                                                                                                                                          |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 03/10/2024 (Thursday)  | 08:15 - 10:00  | Disability-Adjusted Life Year Outcomes (DALYs) \[TBD\]                                                                                                                                                                                                                                                                                                                                                                        |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 10:00 - 10:30  | Tea Break                                                                                                                                                                                                                                                                                                                                                                                                                     |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 10:30 - 12:00  | Capstone Presentations Session 1                                                                                                                                                                                                                                                                                                                                                                                              |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 12:00 - 13:15  | Lunch                                                                                                                                                                                                                                                                                                                                                                                                                         |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 13:15 - 15:00  | Capstone Presentations Session 2                                                                                                                                                                                                                                                                                                                                                                                              |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                        | 15:00          | Certificate Ceremony and Closing Dicussion                                                                                                                                                                                                                                                                                                                                                                                    |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Extra Slides           |                | [2022: Summarizing Model Outputs](https://vchem-vital-workshop-2022.netlify.app/lectures/lec_summarizing-model-outputs#/title-slide)                                                                                                                                                                                                                                                                                          |
|                        |                |                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                        |                | [Bogota: Advanced modeling techniques](lectures/lec_advanced-modeling-techniques.qmd)                                                                                                                                                                                                                                                                                                                                         |
|                        |                |                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                        |                | [Nigeria: Advanced modeling techniques](https://graveja0.github.io/v-brch-nigeria-2023/lectures/lec_advanced-modeling-techniques.html#/title-slide)                                                                                                                                                                                                                                                                           |
+------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[10,20,50\]"}
