---
title: "Recordings"
---

Introductions / Conceptual and Theoretical Foundations / Identifying strategy differences

<https://vitalstrategies.zoom.us/rec/share/J83rYEr5f4EP0uUs2JJEiEm3vpn-WVtztGOKl16iquBPQA49AggCw8bBMRhZui7p.uuAA2YtZhnN5jniE?startTime=1769387347000>

Passcode: \^H\$w.67D

 

Decision trees

<https://vitalstrategies.zoom.us/rec/share/J83rYEr5f4EP0uUs2JJEiEm3vpn-WVtztGOKl16iquBPQA49AggCw8bBMRhZui7p.uuAA2YtZhnN5jniE?startTime=1769396916000>

Passcode: \^H\$w.67D

 

Capstone Example: Mike Bulatao

<https://vitalstrategies.zoom.us/rec/share/Vb-EPvDKsE9S8nB-UbL0AsLNv9dMG2a0Mc2nJWUzf4v2BNfID0DxQRAd8Wiqp1Zp.PSXU_QQ2DhyuSWtS?startTime=1769406205000>

Passcode: \^H\$w.67D

 

AMUA case study

<https://vitalstrategies.zoom.us/rec/share/Vb-EPvDKsE9S8nB-UbL0AsLNv9dMG2a0Mc2nJWUzf4v2BNfID0DxQRAd8Wiqp1Zp.PSXU_QQ2DhyuSWtS?startTime=1769410454000>

Passcode: \^H\$w.67D

 

CEA Fundamentals: Costs (part 1)

<https://vitalstrategies.zoom.us/rec/share/Vb-EPvDKsE9S8nB-UbL0AsLNv9dMG2a0Mc2nJWUzf4v2BNfID0DxQRAd8Wiqp1Zp.PSXU_QQ2DhyuSWtS?startTime=1769410454000>

Passcode: \^H\$w.67D

 

CEA Fundamentals: Costs (part 2)

<https://vitalstrategies.zoom.us/rec/share/jMbfzByu5QcbDUzFcWkraspE5hZah63VF2_4hoV6yMiD1w7WJONOa2ysC4SYKRye.3gKG5wHTQ9oQRZp5?startTime=1769472571000>

Passcode: .pDt5E??

 

CEA Fundamentals: Valuing Outcomes

<https://vitalstrategies.zoom.us/rec/share/jMbfzByu5QcbDUzFcWkraspE5hZah63VF2_4hoV6yMiD1w7WJONOa2ysC4SYKRye.3gKG5wHTQ9oQRZp5?startTime=1769482930000>

Passcode: .pDt5E??

 

Disability-Adjusted Life Years

<https://vitalstrategies.zoom.us/rec/share/jMbfzByu5QcbDUzFcWkraspE5hZah63VF2_4hoV6yMiD1w7WJONOa2ysC4SYKRye.3gKG5wHTQ9oQRZp5?startTime=1769484265000>

Passcode: .pDt5E??

 

Incremental Cost-Effectiveness Analysis

<https://vitalstrategies.zoom.us/rec/share/jMbfzByu5QcbDUzFcWkraspE5hZah63VF2_4hoV6yMiD1w7WJONOa2ysC4SYKRye.3gKG5wHTQ9oQRZp5?startTime=1769493098000>

Passcode: .pDt5E??

**Markov models:**

<https://vitalstrategies.zoom.us/rec/share/dSUW5sFS4o3yUZJtIZU-HhrVqvC3sqjnfBiaD4ABUCk04S6TtFKU95LSG7X91rw.dLyIEDNRhgWG2iss?startTime=1769562912000>

Passcode: ?Zx6wEGb

 

**Rates and probabilities:**

<https://vitalstrategies.zoom.us/rec/share/2esljLJSe_fcrg_RnCFKbOnj8moXkJA-HpKIuKB_K7nHlcZBmSUVOPPbRurfK3Q.-2Es8LpL74Fvcr2j?startTime=1769570173000>

Passcode: ?Zx6wEGb

 

**Incremental CEA case study walkthrough:**

<https://vitalstrategies.zoom.us/rec/share/2esljLJSe_fcrg_RnCFKbOnj8moXkJA-HpKIuKB_K7nHlcZBmSUVOPPbRurfK3Q.-2Es8LpL74Fvcr2j?startTime=1769571955000>

Passcode: ?Zx6wEGb

**Structuring a Markov Model**

<https://vitalstrategies.zoom.us/rec/share/q8yySJj6rwEGTtFeiRm_4z61KF1Jeitv9G_F5VjePGdRw0OgGGfvYtIHqa2HDwKh._oxcwYvN2_wG6Ok4?startTime=1769645737000>

Passcode: +iGr2+wQ

 

**Deterministic, Threshold, and Scenario Analyses**

<https://vitalstrategies.zoom.us/rec/share/q8yySJj6rwEGTtFeiRm_4z61KF1Jeitv9G_F5VjePGdRw0OgGGfvYtIHqa2HDwKh._oxcwYvN2_wG6Ok4?startTime=1769655620000>

Passcode: +iGr2+wQ

 

**Cost-Effectiveness of SBCC and Cessation Services in Reducing Alcohol-Related Harms in the Philippines (Capstone example)**

<https://vitalstrategies.zoom.us/rec/share/q8yySJj6rwEGTtFeiRm_4z61KF1Jeitv9G_F5VjePGdRw0OgGGfvYtIHqa2HDwKh._oxcwYvN2_wG6Ok4?startTime=1769665663000>

Passcode: +iGr2+wQ

**DALYs Case Study (includes Markov and decision trees)**

<https://vitalstrategies.zoom.us/rec/share/HMB2CqPAz9rAHUtFgafH4DOWEJy8ZQbvuZ3uu14n3W4NmB78smqZgZ1PbVoeko8b.wCiQ-YMaJSx9xmg_?startTime=1769732910000>

Passcode: Z4e8Wk=G

 

**Common Errors**

<https://vitalstrategies.zoom.us/rec/share/HMB2CqPAz9rAHUtFgafH4DOWEJy8ZQbvuZ3uu14n3W4NmB78smqZgZ1PbVoeko8b.wCiQ-YMaJSx9xmg_?startTime=1769738691000>

Passcode: Z4e8Wk=G

 
