---
title: "Capstone Topics"
---

# Topics of Each Participant

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
| Topic                                                                                                                                                                                                                                             | Country      | Participant(s)                 |
+===================================================================================================================================================================================================================================================+==============+================================+
| **Maternal Health Waivers**                                                                                                                                                                                                                       | Bangladesh   | -   Manoshi Saha Tuli          |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
| **Cervical Cancer Screening** (No screening vs Visual Inspection with Acetic Acid vs Pap smear screening)                                                                                                                                         | Bangladesh   | -   Mohammad Rashedul HassanMD |
|                                                                                                                                                                                                                                                   |              |                                |
|                                                                                                                                                                                                                                                   |              | -    Omar Qayum                |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
| **Cervical Cancer Screening** (Health facility vs community center screening)                                                                                                                                                                     | Cambodia     | -   Socheata Phou              |
|                                                                                                                                                                                                                                                   |              |                                |
|                                                                                                                                                                                                                                                   |              | -    Ngovlily Sok              |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
| **Gastric Cancer** (No screening versus risk assessment-driven gastric cancer screening)                                                                                                                                                          | China        | -   Shan Jin                   |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
| **Assisted Reproductive Technology** (No ART vs ART patient coverage vs ART insurance coverage)                                                                                                                                                   | China        | -   Huiting Yu                 |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
| **HPV Vaccines** (No screening vs VIA vs VIA + education vs HPV DNA-screening)                                                                                                                                                                    | Ethiopia     | -   Desalegn Ararso            |
|                                                                                                                                                                                                                                                   |              |                                |
|                                                                                                                                                                                                                                                   |              | -    Abdurehman Ibro           |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
| **Neonatal Mortality** (Standard oxygen therapy vs referral to higher-level SNCUs/NICUs vs bubble CPAP devices vs multiple combined methods)                                                                                                      | India        | -   Diksha Gautam              |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
| **Cardiovascular Disease Screening** (One-time Lipoprotein testing vs no lipoprotein testing)                                                                                                                                                     | India        | -   Archana Thakur             |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
| **Cervical Cancer Treatment** (metastatic cervical cancer patient with combination of bevacizumab and Chemotherapy vs chemotherapy only)                                                                                                          | Indonesia    | -   Nana Tristiana Indriasari  |
|                                                                                                                                                                                                                                                   |              |                                |
|                                                                                                                                                                                                                                                   |              | -   Eva Herlinawaty            |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
| **Colorectal Cancer Early Detection** (No screening vs Colonoscopy every 5 years)                                                                                                                                                                 | Lebanon      | -   Caroline Daccache          |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
| **Breast Cancer Screening** (visual inspection with acetic acid (VIA) vs HPV testing)                                                                                                                                                             | Morocco      | -   Chakib Boukhalfa           |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
| **Hypertension** (limited screening locations vs expanding screening corner to all public health centres)                                                                                                                                         | Mozambique   | -   Nelmo Jordao Manjate       |
|                                                                                                                                                                                                                                                   |              |                                |
|                                                                                                                                                                                                                                                   |              | -   Kadira Mamad Selemane Tapu |
|                                                                                                                                                                                                                                                   |              |                                |
|                                                                                                                                                                                                                                                   |              | -   Tania Issufo               |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
| **HPV Vaccination of 15–18 Year Olds** (HPV vaccination limited to girls aged 9-14 years vs Catch-up two-dose HPV vaccination for ages 15-18 vs Catch-up HPV vaccination for ages 15-18 (single-dose schedule) )                                  | Philippines  | -   Nina Fritzie Bruce         |
|                                                                                                                                                                                                                                                   |              |                                |
|                                                                                                                                                                                                                                                   |              | -   Dinnes Karl Garcia         |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
| **Road Accidents** (Current enforcement and awareness activities vs Enhanced enforcement only vs driver education)                                                                                                                                | Rwanda       | -   Mahoro Gisele Uwemeye      |
|                                                                                                                                                                                                                                                   |              |                                |
|                                                                                                                                                                                                                                                   |              | -   Christian Nsanzabaganwa    |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
| **Kidney Transplantation** (Dialysis vs Kidney Transplant)                                                                                                                                                                                        | Senegal      | -   Assietou Fall              |
|                                                                                                                                                                                                                                                   |              |                                |
|                                                                                                                                                                                                                                                   |              | -   Assietou Niang Gueye       |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
| **Rabies** (Passive human rabies surveillance vs animal bite surveillance vs animal bite surveillance with tracking of rabies PEP provision)                                                                                                      | South Africa | -   Lehlohonolo Kumalo         |
|                                                                                                                                                                                                                                                   |              |                                |
|                                                                                                                                                                                                                                                   |              | -   Ruvimbo Chingonzoh         |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
| **Maternal Health** ( no routine postnatal mental health screening vs Routine Facility-Based Postnatal Mental Health Screening vs Integrated ANC-PNC Mental Health Continuum Screening vs Community-Based Screening via Community Health Workers) | Tanzania     | -   Ngereja John Saganya       |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
| **Malaria** (PQ14 vs PQ7 vsTQ)                                                                                                                                                                                                                    | Thailand     | -   Watcharapol Rongdech       |
|                                                                                                                                                                                                                                                   |              |                                |
|                                                                                                                                                                                                                                                   |              | -   Saruttaya Wongsuwanphon    |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
| **TB – Optimizing Active Case Finding** (passive case finding vs targeted mobile X-ray van screening for high-risk groups)                                                                                                                        | Uganda       | -   Deborah Aujo               |
|                                                                                                                                                                                                                                                   |              |                                |
|                                                                                                                                                                                                                                                   |              | -    Aminah Namwabira          |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
| **Thalassemia Screening** ()                                                                                                                                                                                                                      | Vietnam      | -   Tra Nguyen Thi Thu         |
|                                                                                                                                                                                                                                                   |              |                                |
|                                                                                                                                                                                                                                                   |              | -   Tam Hoang Minh             |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
| **Alcohol Abuse** (Status quo vs\                                                                                                                                                                                                                 | Zambia       | -   John Musantu               |
| Minimum unit pricing only vs Public health awareness campaign only vsCombined MUP + awareness campaign)                                                                                                                                           |              |                                |
|                                                                                                                                                                                                                                                   |              | -   Nsanzya Maambo             |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
| **Major Depressive Disorders** (No intervention versus targeted brief interventions.)                                                                                                                                                             | Zimbabwe     | -   Dorcas Hadzizi             |
|                                                                                                                                                                                                                                                   |              |                                |
|                                                                                                                                                                                                                                                   |              | -   Ronald Timbe               |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------------------------+
