---
title: "Small Group Presentations"
subtitle: "Capstone Exercise 1"
format: 
  html:
    link-external-newwindow: true
  pdf:
    toc: false
editor_options: 
  chunk_output_type: console
self-contained: true
editor: source
---

# Objectives

-	Present your draft Background, Objective/Decision Problem, and Strategy Options to your small group

    *Quick, 5-minute presentation. Allow plenty of time for feedback.*

-	Provide feedback on clarity and completeness of descriptions
  - How can the health issue/condition be more clearly described?  
  - Is the decision problem clearly defined? 
  - How well do the strategy options match the background and decision problem? 


# Deliverables

Create initial/draft slides for final presentation that introduce your decision

-	Slide 1 – Title, Team name, and Members
  - Tell us who you are
  
- Slide 2 – Background    
  - What is the health condition/issue you are trying to address and what is the motivation for addressing it?
  
- Slide 3 – Objective
  - What is the decision problem or comparison you will be modeling?
  
-	Slide 4 – Strategy options
  -Describe the status quo and the options you are considering
